name: show_information
description: A mobile application for displaying saved information to others.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  information_data_source:
    path: packages/information_data_source
  information_repository:
    path: packages/information_repository
  objectbox_information_data_source:
    path: packages/objectbox_information_data_source
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  mockingjay: ^0.4.0

flutter:
  uses-material-design: true
