name: information_repository
description: A repository for managing information.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  information_data_source:
    path: ../information_data_source

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.21.0
