name: information_data_source
description: Data source interface and models for providing access to information.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
