name: app

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  flutter_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze lib

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        if: github.event_name == 'push'
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov

  build_android:
    needs: [flutter_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build an APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Android release artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with:
          name: android_release
          path: "build/app/outputs/apk/release"

  build_ios:
    needs: [flutter_tests]
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build for iOS
        run: flutter build ios --release --no-codesign

  release_android:
    if: github.event_name == 'push'
    needs: [build_android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate version variables
        run: |
          echo "VERSION_2ND_PLACE=$((GITHUB_RUN_NUMBER/10))" >> $GITHUB_ENV
          echo "VERSION_3RD_PLACE=$((GITHUB_RUN_NUMBER%10))" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android_release/*.apk"
          tag: v1.${{ env.VERSION_2ND_PLACE }}.${{ env.VERSION_3RD_PLACE }}
